apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-model-cache
  namespace: llm
  labels:
    app.kubernetes.io/part-of: localllm-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
